# Wykrywanie encji nazwanych z Flair

To już ostatnie laboratoria zadaniowe, w związku z tym, jeśli znajdziecie chwilę wolnego czasu, wypełnijcie proszę ankietę: https://docs.google.com/forms/d/1rHPjpL70XdXRD-ILl3AHophPNUk0AhsFus1-mtkUPsI

Pozwoli to mi poprawić laboratoria w przyszłości, z góry dziękuję :)

# Flair

Biblioteka Flair to bardzo popularne narzędzie do tagowania sekwencji. Zaintstalujmy ją

In [1]:
!pip install flair

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 4.4.0 requires importlib-metadata>=4.4; python_version < "3.10", but you have importlib-metadata 3.10.1 which is incompatible.


  Created wheel for gdown: filename=gdown-4.4.0-py3-none-any.whl size=14759 sha256=f53d2f093b03092506dad11dfeaa9ba81cf09bd424f98865647be45cea038d68
  Stored in directory: c:\users\asia\appdata\local\pip\cache\wheels\7d\37\b6\b2a79c75e898c0b8e46ff255102602d7159a10d9af0d80641a
  Created wheel for mpld3: filename=mpld3-0.3-py3-none-any.whl size=116702 sha256=383053503e3659f55c80ecdab225c69881746466815ef9193c47e8bb9b09aaee
  Stored in directory: c:\users\asia\appdata\local\pip\cache\wheels\a6\f4\e6\e40ff9021f6b3854af70fa8ea004f5ab95672817462df08fed
  Created wheel for overrides: filename=overrides-3.1.0-py3-none-any.whl size=10187 sha256=54eb3007ddf832c934d7e0dff96b6f43b92605233cadb9429aeedf4eda44315d
  Stored in directory: c:\users\asia\appdata\local\pip\cache\wheels\7d\11\0e\73fdcb3d71d97e33c230900efe85923ee9d49515d050503174
  Created wheel for sqlitedict: filename=sqlitedict-2.0.0-py3-none-any.whl size=15733 sha256=85b30aadafc6422b25f4479298d082e7ce4f20044e0b18805401b8451b6c9d6c
  Store

In [ ]:
# OPCJONALNE WSPARCIE DLA KART GRAFICZNYCH
# W colabie możemy trenować z wykorzystaniem karty graficznej, dzięki temu trening działa dużo szybciej
# Aby włączyć wsparcie dla karty graficznej musimy:
# 1. w menu 'srodowisko wykonawcze' wybrać `zmien typ srodowiska wykonawczego` i tam `akcelerator sprzętowy` = GPU
# 2. odkomentować linijki poniżej
# import flair, torch
# flair.device = torch.device('cuda:0') 

# Ładowanie zbioru danych i słownika z etykietami.

**Zadanie1: (1 punkt):** Stwórz słownik etykiet z wczytanego korpusu korzystając z funkcji `make_label_dictionary()`. W naszym zbiorze, etykiety do wykrycia występują w kolumnie `ner`, której identyfikator został zapisany w linijce 6. Tutorial: https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md może okazać się pomocny.

Efektem działania powinna być lista etykiet np: 
`Dictionary with 20 tags: <unk>, Variable, Class, Application, User_Interface_Element, Code_Block, Language, Function, Data_Structure, Library, Data_Type, File_Type, File_Name, Version, HTML_XML_Tag, Device, Operating_System, Website, User_Name, Algorithm`

In [2]:
from flair.datasets import NER_ENGLISH_STACKOVERFLOW    # zbiór otagowanych postów na Stacku

corpus = NER_ENGLISH_STACKOVERFLOW().downsample(0.1)   # pobieramy korpus i zmniejszamy jego wielkość
corpus.filter_empty_sentences()                         # usuwamy puste zdania

label_type = 'ner'   # identyfikator pod którym możemy dostać typy etykiet
label_dict = corpus.make_label_dictionary(label_type=label_type)    # TODO
print('\n\nEtykiety do wykrycia')
print(label_dict)

2022-06-01 14:23:54,966 https://raw.githubusercontent.com/jeniyat/StackOverflowNER/master/resources/annotated_ner_data/StackOverflow/train.txt not found in cache, downloading to C:\Users\Asia\AppData\Local\Temp\tmplibrfded


3221198B [00:00, 24593139.13B/s]         

2022-06-01 14:23:55,224 copying C:\Users\Asia\AppData\Local\Temp\tmplibrfded to cache at C:\Users\Asia\.flair\datasets\ner_english_stackoverflow\train.txt


2022-06-01 14:23:55,441 removing temp file C:\Users\Asia\AppData\Local\Temp\tmplibrfded
2022-06-01 14:23:55,897 File train has 741 questions and 897 answers.
2022-06-01 14:23:56,356 https://raw.githubusercontent.com/jeniyat/StackOverflowNER/master/resources/annotated_ner_data/StackOverflow/test.txt not found in cache, downloading to C:\Users\Asia\AppData\Local\Temp\tmp8pvii32g


1093520B [00:00, 7741086.95B/s]          

2022-06-01 14:23:56,978 copying C:\Users\Asia\AppData\Local\Temp\tmp8pvii32g to cache at C:\Users\Asia\.flair\datasets\ner_english_stackoverflow\test.txt


2022-06-01 14:23:57,142 removing temp file C:\Users\Asia\AppData\Local\Temp\tmp8pvii32g
2022-06-01 14:23:57,350 File test has 249 questions and 315 answers.
2022-06-01 14:23:57,816 https://raw.githubusercontent.com/jeniyat/StackOverflowNER/master/resources/annotated_ner_data/StackOverflow/dev.txt not found in cache, downloading to C:\Users\Asia\AppData\Local\Temp\tmp7vfkw8xf


1003586B [00:00, 15139839.71B/s]         

2022-06-01 14:23:58,005 copying C:\Users\Asia\AppData\Local\Temp\tmp7vfkw8xf to cache at C:\Users\Asia\.flair\datasets\ner_english_stackoverflow\dev.txt


2022-06-01 14:23:58,223 removing temp file C:\Users\Asia\AppData\Local\Temp\tmp7vfkw8xf
2022-06-01 14:23:58,540 File dev has 247 questions and 289 answers.
2022-06-01 14:23:58,540 Reading data from C:\Users\Asia\.flair\datasets\ner_english_stackoverflow
2022-06-01 14:23:58,540 Train: C:\Users\Asia\.flair\datasets\ner_english_stackoverflow\train.txt
2022-06-01 14:23:58,540 Dev: C:\Users\Asia\.flair\datasets\ner_english_stackoverflow\dev.txt
2022-06-01 14:23:58,540 Test: C:\Users\Asia\.flair\datasets\ner_english_stackoverflow\test.txt
2022-06-01 14:24:10,085 Filtering empty sentences
2022-06-01 14:24:10,158 Corpus: 926 train + 294 dev + 311 test sentences
2022-06-01 14:24:10,175 Computing label dictionary. Progress:


926it [00:00, 19643.17it/s]

2022-06-01 14:24:10,227 Dictionary created for label 'ner' with 20 values: Class (seen 147 times), Application (seen 119 times), Variable (seen 105 times), Code_Block (seen 92 times), User_Interface_Element (seen 91 times), Library (seen 77 times), Function (seen 67 times), Data_Structure (seen 62 times), Language (seen 59 times), Data_Type (seen 42 times), Version (seen 36 times), File_Name (seen 33 times), Operating_System (seen 27 times), File_Type (seen 23 times), HTML_XML_Tag (seen 21 times), Device (seen 20 times), Website (seen 13 times), User_Name (seen 9 times), Algorithm (seen 6 times)


Etykiety do wykrycia
Dictionary with 20 tags: <unk>, Class, Application, Variable, Code_Block, User_Interface_Element, Library, Function, Data_Structure, Language, Data_Type, Version, File_Name, Operating_System, File_Type, HTML_XML_Tag, Device, Website, User_Name, Algorithm


# Embeddingi

W narzędziu Flair możemy bardzo prosto składać ze sobą różne embeddingi. 

**Zad2 (2 punkty):** Zapoznaj się z działaniem `StackedEmbeddings` opisanego w https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_3_WORD_EMBEDDING.md i zbuduj embeddingi zawierające reprezentacje pochodzące zarówno z Glove jak i Flairowe, oparte na `news-forward`. 

In [4]:
from flair.embeddings import WordEmbeddings, StackedEmbeddings, FlairEmbeddings
from flair.data import Sentence

glove_embedding = WordEmbeddings('glove')
flair_embedding_forward = FlairEmbeddings('news-forward')


embeddings = StackedEmbeddings([glove_embedding,flair_embedding_forward,]) 

sentence = Sentence('The grass is green .')
embeddings.embed(sentence)

for token in sentence:
    print(token)
    print(token.embedding)


Token[0]: "The"
tensor([-3.8194e-02, -2.4487e-01,  7.2812e-01,  ..., -4.4014e-04,
        -3.9301e-02,  1.0601e-02])
Token[1]: "grass"
tensor([-8.1353e-01,  9.4042e-01, -2.4048e-01,  ..., -3.7749e-04,
        -2.3563e-02,  1.1700e-02])
Token[2]: "is"
tensor([-0.5426,  0.4148,  1.0322,  ..., -0.0061,  0.0112,  0.0100])
Token[3]: "green"
tensor([-0.6791,  0.3491, -0.2398,  ..., -0.0026, -0.0118,  0.0455])
Token[4]: "."
tensor([-3.3979e-01,  2.0941e-01,  4.6348e-01,  ..., -2.3405e-04,
         3.8688e-03,  5.7725e-03])


# Tagger i trainer

**Zadanie 3 (2 punkty)** Bazując na treściach opisanych w https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md przygotuj obiekt `SequenceTagger`, którego rozmiar wartswy ukrytej wyniesie 256. Do obiektu tego przekażemy stworzone wcześniej embeddingi, słownik `label_dict` i nazwę kolumny z etykietą ze zmiennej `label_type`. Ustawmy `use_crf` na True.

Przygotuj obiekt `ModelTrainer`, który przyjmie zarówno nasz korpus jak i stworzony przed chwilą `SequenceTagger`.

In [5]:
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer


tagger = SequenceTagger(hidden_size = 256, embeddings = embeddings, tag_dictionary=label_dict, tag_type=label_type, use_crf=True)
trainer = ModelTrainer(tagger, corpus)   # TODO


#stworzony trainer możemy zacząć trenować!
trainer.train('resources/taggers/example-upos',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=5)

# a kiedy wytrenujemy, wczytujemy najlepszy model.
model = SequenceTagger.load('resources/taggers/example-upos/final-model.pt')


2022-06-01 14:33:42,631 SequenceTagger predicts: Dictionary with 77 tags: O, S-Class, B-Class, E-Class, I-Class, S-Application, B-Application, E-Application, I-Application, S-Variable, B-Variable, E-Variable, I-Variable, S-Code_Block, B-Code_Block, E-Code_Block, I-Code_Block, S-User_Interface_Element, B-User_Interface_Element, E-User_Interface_Element, I-User_Interface_Element, S-Library, B-Library, E-Library, I-Library, S-Function, B-Function, E-Function, I-Function, S-Data_Structure, B-Data_Structure, E-Data_Structure, I-Data_Structure, S-Language, B-Language, E-Language, I-Language, S-Data_Type, B-Data_Type, E-Data_Type, I-Data_Type, S-Version, B-Version, E-Version, I-Version, S-File_Name, B-File_Name, E-File_Name, I-File_Name, S-Operating_System
2022-06-01 14:33:42,790 ----------------------------------------------------------------------------------------------------
2022-06-01 14:33:42,790 Model: "SequenceTagger(
  (embeddings): StackedEmbeddings(
    (list_embedding_0): WordEmbe

100%|██████████| 10/10 [00:55<00:00,  5.56s/it]

2022-06-01 14:38:23,166 Evaluating as a multi-label problem: False
2022-06-01 14:38:23,223 DEV : loss 0.6544909477233887 - f1-score (micro avg)  0.0055
2022-06-01 14:38:23,274 BAD EPOCHS (no improvement): 0
2022-06-01 14:38:23,274 saving best model


2022-06-01 14:38:25,391 ----------------------------------------------------------------------------------------------------
2022-06-01 14:38:33,355 epoch 2 - iter 2/29 - loss 0.62154284 - samples/sec: 8.06 - lr: 0.100000
2022-06-01 14:38:43,088 epoch 2 - iter 4/29 - loss 0.58837455 - samples/sec: 6.58 - lr: 0.100000
2022-06-01 14:38:47,948 epoch 2 - iter 6/29 - loss 0.61737519 - samples/sec: 13.18 - lr: 0.100000
2022-06-01 14:38:53,649 epoch 2 - iter 8/29 - loss 0.61750186 - samples/sec: 11.23 - lr: 0.100000
2022-06-01 14:38:58,595 epoch 2 - iter 10/29 - loss 0.62349695 - samples/sec: 12.94 - lr: 0.100000
2022-06-01 14:39:04,287 epoch 2 - iter 12/29 - loss 0.62599367 - samples/sec: 11.24 - lr: 0.100000
2022-06-01 14:39:08,329 epoch 2 - iter 14/29 - loss 0.62428650 - samples/sec: 15.86 - lr: 0.100000
2022-06-01 14:39:14,815 epoch 2 - iter 16/29 - loss 0.63648196 - samples/sec: 9.87 - lr: 0.100000
2022-06-01 14:39:19,600 epoch 2 - iter 18/29 - loss 0.63311866 - samples/sec: 13.38 - lr: 

100%|██████████| 10/10 [00:05<00:00,  1.92it/s]

2022-06-01 14:39:58,445 Evaluating as a multi-label problem: False
2022-06-01 14:39:58,466 DEV : loss 0.5762297511100769 - f1-score (micro avg)  0.0053
2022-06-01 14:39:58,515 BAD EPOCHS (no improvement): 1


2022-06-01 14:39:58,515 ----------------------------------------------------------------------------------------------------
2022-06-01 14:40:02,885 epoch 3 - iter 2/29 - loss 0.41762926 - samples/sec: 14.68 - lr: 0.100000
2022-06-01 14:40:10,481 epoch 3 - iter 4/29 - loss 0.47227542 - samples/sec: 8.43 - lr: 0.100000
2022-06-01 14:40:15,181 epoch 3 - iter 6/29 - loss 0.49683903 - samples/sec: 13.62 - lr: 0.100000
2022-06-01 14:40:19,826 epoch 3 - iter 8/29 - loss 0.54611827 - samples/sec: 13.79 - lr: 0.100000
2022-06-01 14:40:25,806 epoch 3 - iter 10/29 - loss 0.52690637 - samples/sec: 10.71 - lr: 0.100000
2022-06-01 14:40:31,557 epoch 3 - iter 12/29 - loss 0.51981469 - samples/sec: 11.13 - lr: 0.100000
2022-06-01 14:40:38,500 epoch 3 - iter 14/29 - loss 0.52326135 - samples/sec: 9.22 - lr: 0.100000
2022-06-01 14:40:44,532 epoch 3 - iter 16/29 - loss 0.53905127 - samples/sec: 10.62 - lr: 0.100000
2022-06-01 14:40:48,720 epoch 3 - iter 18/29 - loss 0.54055660 - samples/sec: 15.30 - lr:

100%|██████████| 10/10 [00:05<00:00,  1.95it/s]

2022-06-01 14:41:25,916 Evaluating as a multi-label problem: False
2022-06-01 14:41:25,945 DEV : loss 0.5062013268470764 - f1-score (micro avg)  0.0374
2022-06-01 14:41:25,992 BAD EPOCHS (no improvement): 0


2022-06-01 14:41:25,995 saving best model
2022-06-01 14:41:27,741 ----------------------------------------------------------------------------------------------------
2022-06-01 14:41:34,213 epoch 4 - iter 2/29 - loss 0.59642499 - samples/sec: 9.90 - lr: 0.100000
2022-06-01 14:41:40,546 epoch 4 - iter 4/29 - loss 0.58600300 - samples/sec: 10.11 - lr: 0.100000
2022-06-01 14:41:45,576 epoch 4 - iter 6/29 - loss 0.58386443 - samples/sec: 12.72 - lr: 0.100000
2022-06-01 14:41:52,606 epoch 4 - iter 8/29 - loss 0.55467333 - samples/sec: 9.11 - lr: 0.100000
2022-06-01 14:41:57,356 epoch 4 - iter 10/29 - loss 0.55272091 - samples/sec: 13.49 - lr: 0.100000
2022-06-01 14:42:01,275 epoch 4 - iter 12/29 - loss 0.52707172 - samples/sec: 16.33 - lr: 0.100000
2022-06-01 14:42:06,162 epoch 4 - iter 14/29 - loss 0.53597374 - samples/sec: 13.10 - lr: 0.100000
2022-06-01 14:42:11,597 epoch 4 - iter 16/29 - loss 0.52270930 - samples/sec: 11.78 - lr: 0.100000
2022-06-01 14:42:16,418 epoch 4 - iter 18/29 - 

100%|██████████| 10/10 [00:05<00:00,  1.89it/s]

2022-06-01 14:42:56,071 Evaluating as a multi-label problem: False
2022-06-01 14:42:56,097 DEV : loss 0.47923287749290466 - f1-score (micro avg)  0.0238
2022-06-01 14:42:56,145 BAD EPOCHS (no improvement): 1


2022-06-01 14:42:56,145 ----------------------------------------------------------------------------------------------------
2022-06-01 14:43:03,253 epoch 5 - iter 2/29 - loss 0.56557632 - samples/sec: 9.01 - lr: 0.100000
2022-06-01 14:43:07,270 epoch 5 - iter 4/29 - loss 0.46193980 - samples/sec: 15.96 - lr: 0.100000
2022-06-01 14:43:13,500 epoch 5 - iter 6/29 - loss 0.50142779 - samples/sec: 10.28 - lr: 0.100000
2022-06-01 14:43:18,027 epoch 5 - iter 8/29 - loss 0.48265585 - samples/sec: 14.15 - lr: 0.100000
2022-06-01 14:43:22,242 epoch 5 - iter 10/29 - loss 0.49221819 - samples/sec: 15.19 - lr: 0.100000
2022-06-01 14:43:27,566 epoch 5 - iter 12/29 - loss 0.47098771 - samples/sec: 12.02 - lr: 0.100000
2022-06-01 14:43:32,545 epoch 5 - iter 14/29 - loss 0.46919839 - samples/sec: 12.86 - lr: 0.100000
2022-06-01 14:43:39,121 epoch 5 - iter 16/29 - loss 0.47434462 - samples/sec: 9.73 - lr: 0.100000
2022-06-01 14:43:49,168 epoch 5 - iter 18/29 - loss 0.47563757 - samples/sec: 6.37 - lr: 

100%|██████████| 10/10 [00:05<00:00,  1.86it/s]

2022-06-01 14:44:24,403 Evaluating as a multi-label problem: False
2022-06-01 14:44:24,435 DEV : loss 0.45542776584625244 - f1-score (micro avg)  0.1339


2022-06-01 14:44:24,489 BAD EPOCHS (no improvement): 0
2022-06-01 14:44:24,493 saving best model
2022-06-01 14:44:28,435 ----------------------------------------------------------------------------------------------------
2022-06-01 14:44:28,456 loading file resources\taggers\example-upos\best-model.pt
2022-06-01 14:44:29,810 SequenceTagger predicts: Dictionary with 79 tags: O, S-Class, B-Class, E-Class, I-Class, S-Application, B-Application, E-Application, I-Application, S-Variable, B-Variable, E-Variable, I-Variable, S-Code_Block, B-Code_Block, E-Code_Block, I-Code_Block, S-User_Interface_Element, B-User_Interface_Element, E-User_Interface_Element, I-User_Interface_Element, S-Library, B-Library, E-Library, I-Library, S-Function, B-Function, E-Function, I-Function, S-Data_Structure, B-Data_Structure, E-Data_Structure, I-Data_Structure, S-Language, B-Language, E-Language, I-Language, S-Data_Type, B-Data_Type, E-Data_Type, I-Data_Type, S-Version, B-Version, E-Version, I-Version, S-File_

100%|██████████| 10/10 [00:58<00:00,  5.87s/it]

2022-06-01 14:45:28,818 Evaluating as a multi-label problem: False
2022-06-01 14:45:28,850 0.156	0.0503	0.0761	0.045
2022-06-01 14:45:28,853 
Results:
- F-score (micro) 0.0761
- F-score (macro) 0.025
- Accuracy 0.045

By class:
                        precision    recall  f1-score   support

                 Class     0.2381    0.2128    0.2247        47
           Application     0.3529    0.1364    0.1967        44
              Variable     0.0000    0.0000    0.0000        32
            Code_Block     0.0000    0.0000    0.0000        23
              Language     0.0769    0.0417    0.0541        24
              Function     0.0000    0.0000    0.0000        23
User_Interface_Element     0.0000    0.0000    0.0000        26
        Data_Structure     0.0000    0.0000    0.0000        25
               Library     0.0000    0.0000    0.0000        16
               Version     0.0000    0.0000    0.0000        14
             File_Type     0.0000    0.0000    0.0000        14
   

2022-06-01 14:45:30,255 SequenceTagger predicts: Dictionary with 79 tags: O, S-Class, B-Class, E-Class, I-Class, S-Application, B-Application, E-Application, I-Application, S-Variable, B-Variable, E-Variable, I-Variable, S-Code_Block, B-Code_Block, E-Code_Block, I-Code_Block, S-User_Interface_Element, B-User_Interface_Element, E-User_Interface_Element, I-User_Interface_Element, S-Library, B-Library, E-Library, I-Library, S-Function, B-Function, E-Function, I-Function, S-Data_Structure, B-Data_Structure, E-Data_Structure, I-Data_Structure, S-Language, B-Language, E-Language, I-Language, S-Data_Type, B-Data_Type, E-Data_Type, I-Data_Type, S-Version, B-Version, E-Version, I-Version, S-File_Name, B-File_Name, E-File_Name, I-File_Name, S-Operating_System


# Predykcja z udziałem modelu

Jeśli model został wytrenowany, poniżej znajdziemy fragment kodu, który może wykryć encje w zdaniach.

In [6]:
from flair.data import Sentence

# Jeśli nasz model się wyuczył, powinien wykryć Python jako język.
# Uwaga, ponieważ pracujemy na niewielkim podzbiorze zbioru danych (downsample(0.1) próbkuje 10%), 
# otrzymywane wyniki mogą być kiepskiej jakości, najlepiej zwiększyść ilość danych 
# jeśli pracujemy w domu.
sentence = Sentence('huge files can be opened from Python 3.')   # stwórz obiekt zdania
model.predict(sentence)                                         # wykryj encje nazwane
print(sentence.to_tagged_string())                              # wyświetl zdanie i wykryte w nim encje

Sentence: "huge files can be opened from Python 3 ." → ["Python"/Language, "3"/Code_Block]
